[package]
name = "commands"
version = "0.1.0"
edition = "2021"
authors = ["William Muchui <williammuchui584@gmail.com>"]

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
